In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import serial
import time
import keyboard
from IPython.display import clear_output

In [2]:
# connect to Arduino

ser = serial.Serial('COM3', 9600, timeout=1) #check whether the Arduino is really connected with COM3 or adjust the code to the correct COM
                                             #check at settings and check whether Arduino is a connected device
time.sleep(2)

In [3]:
# read write the serial connection at a given sampling rate

def write_read(x):                  #this function takes an input x, which is a switch command and it returns data from the Arduino
    ser.write(bytes(x, 'utf-8'))    #pass the command to Arduino by the serial connection
    data = ser.readline()           #take data from Arduino
    return data                     #return the data to be processed further

In [4]:
values = []
timestamp = []

for j in range(0,4):
    num = '1'                           #power supply = True
    switchtime = time.time()

    for i in range(0,5):
        timestamp.append(time.time()- switchtime)
        clear_output(wait=True)
        value = write_read(num)
        dummy = value.decode().rstrip().split()                                     # transform the byte values that came in...
        values.append(dummy)
       # dum0 = np.array([[int(j)/1024*5 for j in dummy[1:]]])
        print(pd.to_datetime(time.time(), unit= 's'),dummy, 
        #dum0[0],
              '            ', end = "\r")
    
    num = '0'
    switchtime = time.time()
    
    for i in range(0,5):
        timestamp.append(time.time()- switchtime)
        clear_output(wait=True)
        value = write_read(num)
        dummy = value.decode().rstrip().split()                                     # transform the byte values that came in...
        values.append(dummy)
        # dum0 = np.array([[int(j)/1024*5 for j in dummy[1:]]])
        print(pd.to_datetime(time.time(), unit= 's'),dummy, 
        #dum0[0],
              '            ', end = "\r")
    
    
ser.close()       #close the serial port when the reading is stopped. If not done, reconnection with the Arduino is not possible

In [5]:
df = pd.DataFrame(values, 
                  index = timestamp,
                  columns = ['S', 'V0_measured', 'V1_measured', 'V2_measured'])
df.iloc[:,1:] = df.iloc[:,1:].astype(int).div(1024/5)

In [6]:
df#.to_excel('validatie_groen_weerstand_omhoog.xlsx')

          S V0_measured V1_measured V2_measured
0.000000  1    4.990234    2.495117         0.0
1.023160  1    4.995117    3.051758    1.108398
2.049255  1    4.990234     3.47168    1.958008
3.077174  1    4.995117    3.808594    2.617188
4.094285  1    4.990234    4.057617    3.120117
0.000000  0         0.0    1.767578    3.525391
1.033732  0         0.0    1.362305    2.734375
2.056698  0         0.0    1.064453    2.128906
3.079013  0         0.0    0.830078    1.660156
4.098436  0         0.0    0.644531    1.298828
0.000000  1    4.990234    2.998047    1.015625
1.024659  1    4.995117    3.447266     1.90918
2.052867  1    4.995117    3.789062    2.583008
3.076854  1    4.995117    4.047852    3.110352
4.107549  1    4.995117     4.25293    3.510742
0.000000  0         0.0    1.914062    3.828125
1.025515  0         0.0    1.489258    2.973633
2.049652  0         0.0    1.157227    2.324219
3.081159  0         0.0     0.90332    1.811523
4.106722  0         0.0    0.703125    1.416016
0.000000  1    4.990234    3.046875    1.108398
1.017696  1    4.995117    3.481445    1.972656
2.048204  1    4.995117    3.813477    2.641602
3.072556  1    4.990234    4.072266    3.149414
4.098985  1    4.995117    4.272461    3.554688
0.000000  0         0.0    1.933594    3.857422
1.016802  0         0.0    1.503906     3.00293
2.035812  0         0.0    1.176758     2.34375
3.066321  0         0.0    0.913086    1.831055
4.087337  0         0.0    0.712891    1.435547
0.000000  1    4.990234    3.056641    1.118164
1.022308  1    4.995117    3.486328    1.992188
2.055202  1    4.990234    3.823242     2.65625
3.086148  1    4.995117    4.077148    3.168945
4.117752  1    4.995117    4.277344    3.564453
0.000000  0         0.0    1.938477    3.867188
1.028809  0         0.0    1.503906    3.007812
2.049950  0         0.0    1.176758    2.348633
3.075479  0         0.0    0.917969    1.835938
4.107491  0         0.0    0.717773    1.430664

In [16]:
values

[['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 [],
 [],
 [],
 [],
 [],
 ['1', '1023', '511', '00', '0', '0', '0'],
 ['1', '1023', '510', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1021', '510', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '1'],
 [],
 [],
 [],
 [],
 [],
 ['1', '1023', '510', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 [],
 [],
 [],
 [],
 [],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1022', '511', '00', '0', '0', '0'],
 ['1', '1023', '511', '00', '0', '0', '0'],
 [],
 [],
 [],
 [],
 []]